{
 "title": "OpenCTI Dashboard",
 "description": "OpenCTI charm dashboard",
 "tags": [ "nodejs" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{}[2m]) * 100",
     "legendFormat": "User CPU - {{juju_unit}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{}[2m]) * 100",
     "legendFormat": "Sys CPU - {{juju_unit}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds{}", "legendFormat": "{{juju_unit}}" }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(nodejs_version_info{}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{}[1m]))",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{}",
     "legendFormat": "Process Memory - {{juju_unit}}"
    },
    { "expr": "nodejs_heap_size_total_bytes{}", "legendFormat": "Heap Total - {{juju_unit}}" },
    { "expr": "nodejs_heap_size_used_bytes{}", "legendFormat": "Heap Used - {{juju_unit}}" },
    {
     "expr": "nodejs_external_memory_bytes{}",
     "legendFormat": "External Memory - {{juju_unit}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_handles_total{}", "legendFormat": "Active Handler - {{juju_unit}}" },
    { "expr": "nodejs_active_requests_total{}", "legendFormat": "Active Request - {{juju_unit}}" }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{}",
     "legendFormat": "Heap Total - {{juju_unit}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{}",
     "legendFormat": "Heap Used - {{juju_unit}}"
    }
   ]
  }
 ]
}