name: build-cache.yaml
on:
  pull_request:
jobs:
  build-rock:
    name: Build Rock without Cache
    runs-on: ubuntu-latest
    steps:
      - uses: canonical/setup-lxd@v0.1.3
      - uses: actions/checkout@v5.0.0
      - name: Remove Android SDK
        run: sudo rm -rf /usr/local/lib/android
      - uses: canonical/operator-workflows/internal/build@main
        id: build
        with:
          build-plan: |
            {
              "type": "rock",
              "name": "opencti",
              "source_file": "opencti_rock/rockcraft.yaml",
              "source_directory": "opencti_rock",
              "output_type": "registry",
              "output": "${{ github.run_id }}_${{ github.run_attempt }}__build__output__rock__opencti"
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
  build-rock-cache:
    name: Build Rock with Cache
    runs-on: ubuntu-latest
    steps:
      - uses: canonical/setup-lxd@v0.1.3
      - uses: actions/checkout@v5.0.0
      - name: Remove Android SDK
        run: sudo rm -rf /usr/local/lib/android
      - uses: canonical/operator-workflows/internal/build@cache
        id: build
        with:
          build-plan: |
            {
              "type": "rock",
              "name": "opencti",
              "source_file": "opencti_rock/rockcraft.yaml",
              "source_directory": "opencti_rock",
              "output_type": "registry",
              "output": "${{ github.run_id }}_${{ github.run_attempt }}__build__output__rock__opencti_cached"
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
  build-charm:
    name: Build Charm without Cache
    runs-on: ubuntu-latest
    steps:
      - uses: canonical/setup-lxd@v0.1.3
      - uses: actions/checkout@v5.0.0
      - uses: canonical/operator-workflows/internal/build@main
        id: build
        with:
          build-plan: |
            {
              "type": "charm",
              "name": "opencti",
              "source_file": "charmcraft.yaml",
              "source_directory": ".",
              "output_type": "file",
              "output": "${{ github.run_id }}_${{ github.run_attempt }}__build__output__charm__opencti"
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
  build-charm-cache:
    name: Build Charm with Cache
    runs-on: ubuntu-latest
    steps:
      - uses: canonical/setup-lxd@v0.1.3
      - uses: actions/checkout@v5.0.0
      - uses: canonical/operator-workflows/internal/build@cache
        id: build
        with:
          build-plan: |
            {
              "type": "charm",
              "name": "opencti",
              "source_file": "charmcraft.yaml",
              "source_directory": ".",
              "output_type": "file",
              "output": "${{ github.run_id }}_${{ github.run_attempt }}__build__output__charm__opencti_cached"
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
