name: Update Terraform documentation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-docs:
    name: Update Terraform documentation
    uses: canonical/operator-workflows/.github/workflows/generate_terraform_docs.yaml@main
    secrets: inherit
    with:
      terraform-directory: terraform/charm,terraform/product,terraform/product/modules/rabbitmq-server,terraform/product/modules/redis-k8s,terraform/product/modules/s3-integrator
